### ISSUE TITLE
Weapon Fire Sound

### ISSUE THREAD

**Issue by just32** [jwcorle/425_FinalProject#10]
Objective:
Figure out how to add sound when a weapon is fired.

Having sound would be nice. A silent game is lame.

**Comment by co-go** [comment]
@just32 

Don't think this audio is linked with the weapons yet? Didn't hear anything when firing weapons after pulling the latest.
<img width="262" alt="Screen Shot 2020-05-09 at 9 34 01 PM" src="https://user-images.githubusercontent.com/1153142/81488858-ce984480-923c-11ea-9344-bcf3bc53678a.png">

A sound is played when swapping from the Pistol to the P90, it seems cause of this `PlayOnAwake`.
<img width="280" alt="Screen Shot 2020-05-09 at 9 35 22 PM" src="https://user-images.githubusercontent.com/1153142/81488874-ff787980-923c-11ea-9ee7-005562774c1f.png">

Can you fix this for those weapons?
